import { type MigrationInterface, type QueryRunner } from "typeorm";

/**
 * Destructive cutover to Better Auth (docs/adr/013-better-auth-migration.md,
 * docs/auth-migration/03-database-migration-strategy.md §5) — only run
 * after the new auth path was proven end-to-end (Fase 7 rehearsal, the real
 * cutover's own vertical slice, docs/backend/authentication/BETTER_AUTH_CUTOVER_SOURCE_OF_TRUTH.md).
 *
 * Base auto-generated by `migration:generate` from the `UserEntity` diff
 * (drop `password_hash`, `id` stops self-generating). Hand-added (TypeORM's
 * generator has no entity for either, so it can't see them):
 * - `FOREIGN KEY (id) REFERENCES "user"(id)` — the profile-table link to
 *   Better Auth's own `user` table (docs/adr/013, "Propiedad del schema").
 *   Every existing row already has a matching `"user"` row with the same id
 *   (`migrate-users-to-better-auth.ts`, since removed — its one-time job is
 *   done) — this ADD CONSTRAINT is expected to succeed immediately, not a
 *   leap of faith.
 * - `DROP TABLE "refresh_tokens"` — superseded by Better Auth's own
 *   `session` table; `AUTH-02` (docs/auth-migration/01-auth-audit.md, the
 *   missing FK this table never had) is moot once it no longer exists.
 */
export class AlterUsersForBetterAuthCutover1788285369312 implements MigrationInterface {
    name = 'AlterUsersForBetterAuthCutover1788285369312'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "role_assignments" DROP CONSTRAINT "FK_d91c8ac0c10fd8c6acdcc5ee946"`);
        await queryRunner.query(`ALTER TABLE "audit_events" DROP CONSTRAINT "FK_da4e1f7755a2ab9a8b7ddefaa4d"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "audit_events" ADD CONSTRAINT "FK_da4e1f7755a2ab9a8b7ddefaa4d" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_assignments" ADD CONSTRAINT "FK_d91c8ac0c10fd8c6acdcc5ee946" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_id_better_auth_user" FOREIGN KEY ("id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying(64) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "revoked_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens"  ("user_id") `);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_id_better_auth_user"`);
        await queryRunner.query(`ALTER TABLE "role_assignments" DROP CONSTRAINT "FK_d91c8ac0c10fd8c6acdcc5ee946"`);
        await queryRunner.query(`ALTER TABLE "audit_events" DROP CONSTRAINT "FK_da4e1f7755a2ab9a8b7ddefaa4d"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "audit_events" ADD CONSTRAINT "FK_da4e1f7755a2ab9a8b7ddefaa4d" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_assignments" ADD CONSTRAINT "FK_d91c8ac0c10fd8c6acdcc5ee946" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        // The real hashes were physically deleted by `up()` and cannot be
        // recovered by this `down()` — restoring the actual column back to
        // a genuinely usable state (not just present) requires the pg_dump
        // backup taken before this migration ever ran
        // (docs/backend/authentication/BETTER_AUTH_CUTOVER_SOURCE_OF_TRUTH.md).
        // A placeholder default only keeps this rollback from crashing on a
        // non-empty table (NOT NULL) — every row would need a real reset
        // afterward.
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password_hash" DROP DEFAULT`);
    }

}
