export const portalDetailPage = {
  subtitle: 'Detalle del portal y sus aliados registrados',
  summary: {
    totalAliados: 'Aliados totales',
    activeAliados: 'Aliados activos',
    transacciones: 'Transacciones acumuladas',
    totalProcesado: 'Total procesado',
  },
  aliadosCard: {
    titlePrefix: 'Aliados de ',
    countSuffix: 'aliados registrados',
    newAliado: 'Nuevo aliado',
  },
  columns: {
    aliado: 'ALIADO',
    tipo: 'TIPO',
    estado: 'ESTADO',
    transacciones: 'TRANSACCIONES',
    totalProcesado: 'TOTAL PROCESADO',
    ultimaActividad: 'ÚLTIMA ACTIVIDAD',
  },
  sinActividad: 'Sin actividad',
  open: 'Abrir →',
  notFound: 'No se encontró el portal solicitado.',
  createModal: {
    title: 'Crear nuevo aliado',
    subtitle: 'Completa la información para crear un nuevo comercio aliado en este portal.',
    generalSection: 'INFORMACIÓN GENERAL',
    contactSection: 'INFORMACIÓN DE CONTACTO',
    tradeNameLabel: 'Nombre comercial',
    tradeNamePlaceholder: 'Ej. Supermercado La 14',
    legalNameLabel: 'Razón social',
    legalNamePlaceholder: 'Ej. La 14 S.A.S.',
    taxIdLabel: 'NIT',
    taxIdPlaceholder: 'Ej. 900123456-1',
    categoryLabel: 'Categoría',
    categoryPlaceholder: 'Selecciona una categoría',
    noCategoriesError: 'Este portal todavía no tiene categorías creadas — no se puede registrar un aliado.',
    contactNameLabel: 'Nombre de contacto',
    contactEmailLabel: 'Email',
    contactPhoneLabel: 'Teléfono',
    addressLabel: 'Dirección',
    cityLabel: 'Ciudad',
    requiredError: 'Completa todos los campos obligatorios.',
  },
  toasts: { created: 'Aliado creado correctamente.' },
} as const;
